example.property: "I AM THE DEFAULT OR BASEMENT"

spring:
  datasource:
    driverClassName: "org.h2.Driver"
    url: "jdbc:h2:mem:confsvr"
    username: "sa"
    password: ""
    testWhileIdle: true
    validationQuery: "SELECT 1"
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: "org.hibernate.dialect.H2Dialect"
