spring:
  application:
    name: oauth2-server

  security:
    oauth2:
      client:
        client-id:

server.port: 8901

management.endpoints.web.exposure.include: "*"
logging:
  level:
    org.springframework: "DEBUG"
